language: python
python:
- 3.6
install: pip install -U tox-travis
script: echo test
deploy:
  provider: pypi
  user: terrycain
  distributions: sdist bdist_wheel
  password:
    secure: 2qoGjCe8+uQ/xOMuUrFoNzT/iIT8lbJaeOZEVzyQXkPIsYwa7N4XLEBITK/mlZuClQPh0KyoAjta/pi+QdX/E61JoqexNCNXYWzE48M5cguEzikrW5v5N1gSHeGV4VI6IQ1CQP2MaSIq25zO4z/0/H0g7SDzINJbgCBBzfdlY3NHrZZotE9bImBPohuTzSUjJPJfHaujCD2qbtR4j+quVvMZ8X439APFJ/PvobGunsqxGVZ7r2Amu0GeZzDAQwajm0huDxJmIrMLv0i8txiK0TmLLYd9udybAftKlawSHr8ovSlRY8KBre+ncN7dKf5X4IUGAxATkOuKSlJmr9IiJCfO6yBYXvRkfz5BSo9FWrzCY5kI+Zy7a0lMCJVroE/LNUe0BN6j043GemSUNHaR0zN3bjlfHbNc6cEhzgUjAoYYqn2hQGvICzq/ZR03C775q73ImiHsr/shU/TN85zZidyrc3DFFQMO5/vDB7K6Uzhk4G/tuSGDoET1ACPvzttkrGMddoUQ5nlgeFXtXO27x30KWtuRQTNEHwuXaWs8i2hGRkp3i15gozVMbMJYRdJgAGLmkgbihJGaZFZSfrF8Dv705hIzz88j8Aj2LEK7dvJdpK6jK1ZsD+pjPc4/55FoDtQxYocwAA1ZxfhsLtCNAaV8LUlGGWdCIGPrll6WIGk=
  on:
    tags: true
    repo: terrycain/sanic-openid-provider
    all_branches: true
    python: 3.6
