language: python

python:
  - 3.6

install: pip install -U tox-travis

script: echo test

deploy:
  provider: pypi
  user: terrycain
  distributions: sdist bdist_wheel
  password:
    secure: bNEdUEQHRqsgSBw7jixWZVID7/YTBGll1IdymKApJf6iRRjZY7zih4CIh5ygT5ZuDqAXYiB9RMOsRm1Rhk0QQ7/FRcLAh+5HbOpcLIITrmNn26+I7ojhBGU+BzhgCL1ar9MQuHJwY3ot3WUhjdX11bjODhwrzfW49qkQ7a99B2k+zm8VvNH/X+vSyGH1TMlrTgutRJ2kd6fM+IvT+siFdz1nrswun2rtsFqTs4/qoNfSQflxOccKLlaaAMItQ63/jSg2VtBJNLDzeZQTcaXYTN+HC0iTNxk8I5Skkcgyx8Hn8qG/oNkS2MPnIWK75Gb542QgFsesySVUW2/28UlAYOEqt5d2Stuf5xYK5HCDMGVoPW/eYSjyotZuYUp/WEv5/exXWBvhmfw5tZeFQ1y/2SyddQn+XtDgf0HqTOh3H/NMu0MvGNSspCD/ULCqKdmx+hX/8iNxs9B9ZJs661s/hMh6Xtx1ABVtqCHREeTk6ss479eD1NySYRyD9hbpfcaPq9HhNL0Xq6E5d3l+sUZEkRDzleTPugUcE8nxjgHRxAadek0ipLAd+HCTa67cUU9rypIysfRVGDCzyu5TS+dzS72lGk2QZ751Az9pFUb4FMKg2AS4xGrJhOFuJoHDkcGludi8bVYAOH2aO7Fzg/jrBvqvplptO2pWaN+xyHzFMIc=
  on:
    tags: true
    repo: terrycain/sanic-openid-provider
    all_branches: true
    python: 3.6
