language: python
python:
- 3.6
install: pip install -U tox-travis
script: echo test
deploy:
  provider: pypi
  user: terrycain
  distributions: sdist bdist_wheel
  password:
    secure: KXc6TRtB2ziC0EJ6AckDE4+Joi6cqh1pdfkgjkP86WDD+mVGKecZjhs5jehCrLRECpisxFd3O4hU51Bdq/9W8VLkDYMmBitszrZ0P9FBxdbKIqNTjST+cMQ7xuWDM9l4yVB7Jg6+54yP0kcvfiNCra83DUAy/3qf5ue0OOpSdENEaQaKnS9UaE7RplAeGZCRGTzdmb5j6eLosACNz+26nvfuK6LLD600trEoJEFs09vxBLouXhde2dcpRojaIfGCt1C01L5ZIEpVvQZuAxEogdBgcc5q154Jn0NPU/G0cbSrM/7hk4ooIeKkiLT8fmgFec7KP09iZWAraqIkCElWutgOZ1U3FytjweP4jZIuECQ+wR18PvB1WoyRQURj8ysTgquZy4zjXoKFmxlHAJ4Kw4oZOgA2jgviurM7POf1ptg/I/r+yVml1hn3+p5Jzsvwi/UWeF1NrqsV1qh4CL9m6T4iea5LIpY4Klb+PUpRprC1/XET4rc5GQhZVY10UynTqmPn9OVZC4/h2kTj4YNhEBGiC5wkInEmWsPhreAsFFbmuO3t8GfUZBc95gKP0ieL2FoXBSBLnOuGf79ofcGSFm5BCpdVR4EGthQXetZMO3NO1Yp+QgNwZGvSnvD55FMp5pWPzfLGwIfcV+tMptUJ0JZVKYxN5Jl2PKDrECo1rpo=
  on:
    tags: true
    repo: terrycain/sanic-openid-provider
    all_branches: true
    python: 3.6
